[package]
name = "hello"
version = "0.1.0"
authors = ["wiz"]
edition = "2018"

[dependencies]
async-std = "1.9.0"
async-trait = "0.1.42"
futures = "0.3.12"
tokio = {version = "0.2.21", features = ["macros"]}
